-- 1. Create the Products table
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text,
  price numeric,
  description text,
  image text,
  stock integer default 0,
  category text
);

-- 2. Create the Messages table (for chat)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender text,
  content text,
  timestamp timestamptz default now(),
  "chatId" text,
  "isAdmin" boolean default false
);

-- 3. Create the Users table (for custom auth)
create table if not exists users (
  id bigint generated by default as identity primary key,
  username text unique,
  password text,
  role text default 'user'
);

-- 4. Enable Public Access (Since we use a Publishable Key on the server)
-- Note: In a strict production environment, you would use RLS policies with authenticated users.
alter table products enable row level security;
create policy "Public Access Products" on products for all using (true) with check (true);

alter table messages enable row level security;
create policy "Public Access Messages" on messages for all using (true) with check (true);

alter table users enable row level security;
create policy "Public Access Users" on users for all using (true) with check (true);

-- 5. Seed the Admin User
-- Password is 'admin123' hashed with bcrypt
delete from users where username = 'admin';
insert into users (username, password, role)
values ('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'admin');

-- 6. Seed Initial Products
insert into products (name, price, description, image, stock, category) values
('Pastel oversized hoodie', 45.00, 'Soft, comfortable, and perfect for a relaxed look.', 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 20, 'Tops'),
('Beige linen trousers', 55.00, 'Breathable linen trousers with a relaxed fit.', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 15, 'Bottoms'),
('Minimalist white sneakers', 89.00, 'Clean design, durable leather, and all-day comfort.', 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 10, 'Shoes'),
('Soft knit cardigan', 60.00, 'A cozy layer for chilly evenings.', 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 5, 'Tops'),
('Silk slip dress', 120.00, 'Elegant and timeless.', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 8, 'Dresses'),
('Canvas tote bag', 25.00, 'Durable and spacious.', 'https://images.unsplash.com/photo-1544816155-12df9643f363?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 50, 'Accessories');
